DOWNLOADED_PATH = "./ressources/downloaded"
UNCONVERTED_PATH = "./ressources/unconverted"
CONVERTED_PATH = "./ressources/converted"
USED_PATH = "./ressources/used"
FILE_EXTENSION = "webm"
FILE_EXTENSION_CONVERTED = "mp3"
